# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :openmaru,
  ecto_repos: [Openmaru.Repo],
  generators: [timestamp_type: :utc_datetime_usec, binary_id: true]

# SPEC-02 §2: uuid (v7, generated by Openmaru.Schema) primary keys, usec timestamps.
config :openmaru, Openmaru.Repo,
  migration_primary_key: [type: :uuid],
  migration_foreign_key: [type: :uuid],
  migration_timestamps: [type: :utc_datetime_usec]

# Builds maru_nif with the `test-helpers` cargo feature (Openmaru.Lang.panic_test/0) for
# tests. Rustler copies the library to the shared priv/native/, so dev must build the
# same artifact or a dev compile would replace the test build. Never enabled in prod.
config :openmaru, nif_test_helpers: config_env() in [:dev, :test]

config :openmaru, Oban,
  engine: Oban.Engines.Basic,
  repo: Openmaru.Repo,
  queues: [default: 10, ledger: 5, webhooks: 10, gateway: 10, runtime: 5, scheduled: 5],
  plugins: [
    {Oban.Plugins.Pruner, max_age: 7 * 24 * 3600},
    {Oban.Plugins.Cron, crontab: [{"17 * * * *", Openmaru.Accounts.PruneWorker}]}
  ]

# C01 accounts. Dev/test values; config/runtime.exs sets production ones.
# WebAuthn relying party: the web app's origin (Vite dev server).
config :openmaru, Openmaru.Accounts.WebAuthn,
  rp_id: "localhost",
  rp_name: "openmaru",
  origin: "http://localhost:5173"

# OAuth providers are enabled by a client_id (config/runtime.exs reads them from env).
config :openmaru, Openmaru.Accounts.OAuth, providers: [github: [], google: []]

# Key for the audit log's IP hash (Openmaru.Audit); derived from SECRET_KEY_BASE in prod.
config :openmaru, Openmaru.Audit, ip_hash_key: "dev-only audit ip hash key"

# Where OAuth callbacks send the browser.
config :openmaru, :web_url, "http://localhost:5173"

# Configure the endpoint
config :openmaru, OpenmaruWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [json: OpenmaruWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: Openmaru.PubSub

# Configure Elixir's Logger
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# SPEC-09 §3: redact credentials from Phoenix's request parameter logs (keys containing
# these strings), e.g. OAuth `code` and WebAuthn `credential` (C01).
config :phoenix, :filter_parameters, ~w(password token secret key code credential)

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
