# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :openmaru,
  ecto_repos: [Openmaru.Repo],
  generators: [timestamp_type: :utc_datetime_usec, binary_id: true]

# SPEC-02 §2: uuid (v7, generated by Openmaru.Schema) primary keys, usec timestamps.
config :openmaru, Openmaru.Repo,
  migration_primary_key: [type: :uuid],
  migration_foreign_key: [type: :uuid],
  migration_timestamps: [type: :utc_datetime_usec]

config :openmaru, Oban,
  engine: Oban.Engines.Basic,
  repo: Openmaru.Repo,
  queues: [default: 10, ledger: 5, webhooks: 10, gateway: 10, runtime: 5, scheduled: 5],
  plugins: [
    {Oban.Plugins.Pruner, max_age: 7 * 24 * 3600},
    {Oban.Plugins.Cron, crontab: []}
  ]

# Configure the endpoint
config :openmaru, OpenmaruWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [json: OpenmaruWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: Openmaru.PubSub

# Configure Elixir's Logger
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
