defmodule Openmaru.UUIDv7 do
  @moduledoc """
  UUIDv7 (RFC 9562) generation and an `Ecto.Type` for UUIDv7 primary keys.

  Layout: 48-bit Unix milliseconds, version `7`, a 12-bit counter (`rand_a`, RFC 9562
  §6.2 method 1), the `10` variant, and 62 random bits. The counter starts at a random
  value in the lower half of its range each millisecond and increments for every id
  generated in the same process during that millisecond; on overflow the timestamp
  borrows the next millisecond. Ids generated by one process are therefore strictly
  increasing. Ids from different processes are unique but only ordered to the
  millisecond.

  Values are the canonical lowercase string form, like `Ecto.UUID`.
  """

  use Ecto.Type

  @state_key {__MODULE__, :last}
  @counter_max 0xFFF

  @type t :: <<_::288>>

  @doc "Generates a UUIDv7 string."
  @spec generate() :: t()
  def generate do
    {ms, counter} = next_timestamp()
    <<rand::62, _::2>> = :crypto.strong_rand_bytes(8)
    {:ok, uuid} = Ecto.UUID.load(<<ms::48, 7::4, counter::12, 0b10::2, rand::62>>)
    uuid
  end

  defp next_timestamp do
    now = System.system_time(:millisecond)

    state =
      case Process.get(@state_key) do
        {last_ms, last_counter} when now <= last_ms and last_counter < @counter_max ->
          {last_ms, last_counter + 1}

        {last_ms, _counter} when now <= last_ms ->
          {last_ms + 1, random_counter()}

        _ ->
          {now, random_counter()}
      end

    Process.put(@state_key, state)
    state
  end

  defp random_counter do
    <<counter::11, _::5>> = :crypto.strong_rand_bytes(2)
    counter
  end

  @impl Ecto.Type
  def type, do: :uuid

  @impl Ecto.Type
  defdelegate cast(value), to: Ecto.UUID

  @impl Ecto.Type
  defdelegate dump(value), to: Ecto.UUID

  @impl Ecto.Type
  defdelegate load(value), to: Ecto.UUID

  @impl Ecto.Type
  def autogenerate, do: generate()
end
